name: Windows System Analysis

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Baixar Otimizador e Configurar
        shell: pwsh
        run: |
          # 1. Baixa o seu arquivo Otimizar.ps1 do seu repositório
          $url = 'https://raw.githubusercontent.com/velilha/monitor10/main/Otimizar.ps1'
          Invoke-WebRequest -Uri $url -OutFile "C:\Users\runneradmin\Desktop\Otimizar.ps1"
          
          # 2. Habilita o Acesso Remoto (RDP)
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
          # 3. Cria o gatilho automático (o arquivo .vbs que vai rodar o script no login)
          $vbs = 'CreateObject("WScript.Shell").Run "powershell -WindowStyle Hidden -ExecutionPolicy Bypass -File C:\Users\runneradmin\Desktop\Otimizar.ps1", 0, False'
          Set-Content -Path "C:\Users\runneradmin\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\ExecOtimizacao.vbs" -Value $vbs

      - name: Iniciar Tunel Cloudflare
        shell: pwsh
        run: |
          # 1. Baixa o Cloudflare
          Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"
          
          # 2. Inicia o túnel e redireciona a saída para log
          Start-Process -FilePath ".\cloudflared.exe" -ArgumentList "tunnel --url tcp://localhost:3389" -RedirectStandardError "tunnel.log" -RedirectStandardOutput "tunnel.log"
          
          # 3. Aguarda para gerar o link e exibe no log
          Start-Sleep -Seconds 20
          Write-Host "--- LINK DO TUNEL ABAIXO ---"
          Get-Content tunnel.log | Select-String "trycloudflare.com"
          
          # 4. Mantém o tunel rodando
          Start-Sleep -Seconds 21600
