name: Windows System Analysis

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Baixar Otimizador e Configurar
        shell: pwsh
        run: |
          # Baixa o script do seu repositório
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/velilha/monitor10/main/Otimizar.ps1" -OutFile "C:\Users\runneradmin\Desktop\Otimizar.ps1"
          
          # Habilita RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
          # Gatilho para rodar o script no login
          $vbs = 'CreateObject("WScript.Shell").Run "powershell -WindowStyle Hidden -ExecutionPolicy Bypass -File C:\Users\runneradmin\Desktop\Otimizar.ps1", 0, False'
          Set-Content -Path "C:\Users\runneradmin\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\ExecOtimizacao.vbs" -Value $vbs

      - name: Iniciar Tunel Cloudflare
        shell: pwsh
        run: |
          # Baixa o cloudflared
          Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"
          
          # Inicia o túnel enviando a saída para um arquivo
          Start-Process -FilePath ".\cloudflared.exe" -ArgumentList "tunnel --url tcp://localhost:3389" -RedirectStandardOutput "tunnel.log"
          
          # Espera o tunel estabilizar
          Start-Sleep -Seconds 20
          
          # Exibe o link no log do GitHub
          Write-Host "--- LINK DO TUNEL ABAIXO ---"
          Get-Content tunnel.log | Select-String "trycloudflare.com"
          
          Start-Sleep -Seconds 21600
