name: Windows System Analysis

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Configuração Ultrarrápida
        shell: pwsh
        run: |
          # 1. Configuração de Idioma Otimizada
          # Se o idioma já existir, ele pula a instalação pesada
          if (!(Get-WinUserLanguageList).LanguageTag.Contains("pt-BR")) {
              Install-Language pt-BR
          }
          Set-WinUILanguageOverride -Language pt-BR
          Set-WinSystemLocale -SystemLocale pt-BR
          
          # 2. Desativação agressiva de serviços (Performance Máxima)
          $servicos = @("wuauserv", "bits", "dosvc", "DiagTrack", "WerSvc", "WbioSrvc", "Spooler", "WSearch", "MapsBroker", "dmwappushservice", "bthserv", "PhoneSvc", "lfsvc")
          foreach ($s in $servicos) {
            Stop-Service -Name $s -Force -ErrorAction SilentlyContinue
            Set-Service -Name $s -StartupType Disabled -ErrorAction SilentlyContinue
          }
          
          # 3. Bloqueios de Telemetria (Via registro é instantâneo)
          reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f
          
          # 4. Interface (Modo Escuro e Performance)
          New-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" -Name "SystemUsesLightTheme" -Value 0 -Force | Out-Null
          Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects" -Name "VisualFXSetting" -Value 2
          
          # 5. Habilitar Acesso Remoto
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Iniciar Tunel
        shell: pwsh
        run: |
          # Download do tunel (O Cloudflare é leve e baixa rápido)
          curl.exe -L --output cloudflared.exe https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe
          Start-Process ./cloudflared.exe -ArgumentList "tunnel --url tcp://localhost:3389" -WindowStyle Hidden
          Write-Host "Tunel iniciado!"
          Start-Sleep -Seconds 21600
