name: Cloudflare Tunnel RDP
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Baixar Cloudflared
        run: |
          Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"

      - name: Iniciar Túnel RDP
        run: |
          # O túnel vai gerar o link no log do GitHub
          .\cloudflared.exe tunnel --url tcp://localhost:3389
