name: WindowsNativoGratis
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Configurar Senha e RDP
        run: |
          # Define a senha do usuário padrão do GitHub
          net user runneradmin SenhaForte123!
          # Libera o acesso remoto no firewall e no sistema
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
      - name: Gerar Link Aleatorio Cloudflare
        shell: pwsh
        run: |
          # Baixa o executável direto (mais rápido e sem erro de instalação)
          Invoke-WebRequest -Uri "https://github.com" -OutFile "cf.exe"
          
          # Este comando CRIA o link aleatório .trycloudflare.com nos logs
          .\cf.exe tunnel --url tcp://localhost:3389
